### ISSUE TITLE
Minimal Example for Firestore on Dart VM

### ISSUE THREAD

**Issue by putraxor** [fluttercommunity/firebase_flutter_sdk#6]
Hi, I'm currenty testing  this SDK on Dart VM but I got some errors look like this:
```
D:FirebaseFirestore           ||Firebase Auth not available, falling back to unauthenticated usage.
D:FirestoreClient             ||Initializing. user=null
D:SQLitePersistence           ||Starting SQLite persistance
Unhandled exception:
NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call()
#0      SQLitePersistence._openDb (package:firebase_firestore/src/firebase/firestore/local/sqlite_persistence.dart:192:43)
<asynchronous suspension>
#1      SQLitePersistence.start (package:firebase_firestore/src/firebase/firestore/local/sqlite_persistence.dart:92:17)
<asynchronous suspension>
#2      FirestoreClient._initialize (package:firebase_firestore/src/firebase/firestore/core/firestore_client.dart:201:23)
<asynchronous suspension>
#3      FirestoreClient.initialize (package:firebase_firestore/src/firebase/firestore/core/firestore_client.dart:92:18)
<asynchronous suspension>
#4      FirebaseFirestore.newInstance (package:firebase_firestore/src/firebase/firestore/firebase_firestore.dart:106:58)
<asynchronous suspension>
#5      main (file:///Users/putraxor/Desktop/dart_gae/bin/main.dart:25:43)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

and my code :
```java
import 'package:firebase_firestore/firebase_firestore.dart';
import 'package:firebase_common/firebase_common.dart';

main(List<String> args) async {
  var options = FirebaseOptions(
    apiKey: "*****************",
    projectId: "*****************",
    storageBucket: "*****************.appspot.com",
    applicationId: '*****************',
    databaseUrl: 'https://*****************.firebaseio.com',
    gcmSenderId: '*****************',
  );

  Future<bool> isNetWorkConnected() async {
    return true;
  }

  var app = FirebaseApp.withOptions(
    options,
    null,
    isNetWorkConnected,
    "basisdata",
  );

  var firestore = await FirebaseFirestore.newInstance(app, "default");
}
```
is there a mistake on my code?

**Comment by putraxor** [comment]
Okay, after reading the test carefully 
```
  var firestore = await FirebaseFirestore.getInstance(app,
      openDatabase: DatabaseMock.create);
```
that code works.
I wonder how to use service account credential for the auth provider and how to disable debug log

**Comment by long1eu** [comment]
Let's keep this open until we add a good example for this.

**Comment by putraxor** [comment]
Is this qualified to be a good example? [vm_example](https://github.com/putraxor/firebase_dart_sdk/tree/master/examples/vm_example)

**Comment by long1eu** [comment]
Looks awesome. Sure do and we can talk there.
